#Tardis Tools Mod 0.0.1.0

modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="MIT"

[[mods]] #mandatory

modId="toolmod" #mandatory
version="0.0.1.0" #mandatory
displayName="Tardis Tool Mod" #mandatory
logoFile="BlueBox.png" #optional
credits="Mom and KD got me into this." #optional
authors="Dave does not do pretty" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Some different tools and a teleport staff
'''

[[dependencies.toolmod]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.toolmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
